[package]
name = "memtest-gpu-ecc"
version = "0.0.0"
edition = "2021"
authors = ["Brandon Christoffer <me@brandonchristoffer.com>"]

[dependencies]
ash = { version = "0.37.0", default-features = false, features = ["linked", "debug"] }
